sudo: true 

services:
  - docker

language: python

python:
    - '2.7'
before_install:
    - git config --global user.email "r.browne@f5.com"
    - git config --global user.name "richbrowne"
install:
    - pip install hacking
    - sudo apt-get update
    - sudo apt-get install git -y
script:
    - flake8 f5_openstack_agent
    - git clone https://github.com/richbrowne/f5-openstack-agent-rpmdist.git rpmdist
    - docker build -t centos7-pkg-builder ./rpmdist/Docker/redhat/7
    - docker run --privileged -v pwd:/var/bdir:rw centos7-pkg-builder /bin/bash /build-rpms.sh
